import type { Metadata } from "next";
import type { ReactNode } from 'react';

import Providers from '@/src/components/Providers';
import Header from '@/src/components/Header';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: ReactNode }) {
  return (
      <html lang="en">
      <body>
      <Providers>
        <Header />
        {children}
      </Providers>
      </body>
      </html>
  );
}